### ISSUE TITLE
World Corruption

### ISSUE THREAD

**Issue by DipsWW** [Syer10/ImpactFlux-Modpack#93]
This have happened to be twice now, my game suddenly freeze and exit with exitcode -1. Then after i've loaded the game backup and enter my world I see where I am in the world in about a second then it exits with exitcode -1 agian. Sorry for my bad english.

Crashlog from first intial crash/corruption
https://www.dropbox.com/s/00d8ryz079zjza5/crash-2015-03-06_16.07.46-server.txt?dl=0

Crashlog from when I tried re-entering the world
https://www.dropbox.com/s/nacqa6cs9e552m2/crash-2015-03-06_16.27.14-server.txt?dl=0

**Comment by Syer10** [comment]
Try removing fastcraft and see if the crash happens again.

**Comment by DipsWW** [comment]
Removed Fastcraft, got the same crash
Crashlog:
https://www.dropbox.com/s/29mdr5ei43jlrhk/crash-2015-03-07_12.00.03-server.txt?dl=0

**Comment by Syer10** [comment]
now try removing FloatingRuins

**Comment by DipsWW** [comment]
Removed FloatingRuins, still crashed
Crashlog:
https://www.dropbox.com/s/4k4hh4g3izwcai4/crash-2015-03-08_00.04.36-server.txt?dl=0
