### ISSUE TITLE
server files

### ISSUE THREAD

**Issue by coetyler** [Syer10/ImpactFlux-Modpack#94]
Not really an issue but i didnt know where else to put this but are there any server files for this?

**Comment by Syer10** [comment]
This is server compatible, I have not made any specific files for it but if you make a server with the forge installer, copy the mods, configs, and scripts to the folder you directed the forge installer to. You can make a server if you remove the mods that would crash the server like journymap(maybe minemenu).

**Comment by coetyler** [comment]
okay thank you
