### ISSUE TITLE
Curse Client

### ISSUE THREAD

**Issue by DipsWW** [Syer10/ImpactFlux-Modpack#95]
In case you didnt already know but some time ago curse released a modpack client where anyone can uplode and install modpacks. You dont even need permission to use curse mods as they automatically get downloaded from the mod authors own curse profile.

You should definitely consider adding you modpack to the curse client as it would make downloading and playing, also updating the modpack easier for both you and the players.

Please add the label "Needs Discussion"

**Comment by Syer10** [comment]
I atcully have added it to the curse launcher. It is here if you would like to download it, I had to remove factorization beause of the 3rd party rules but its all there.
http://minecraft.curseforge.com/modpacks/231120-impactflux
